# GENERATED by dgen from c.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil, Span, String
from dgen.dialects.index import Index

c = Dialect("c")

@dataclass(frozen=True, eq=False)
class CStruct(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(frozen=True, eq=False)
class CUnion(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(eq=False, kw_only=True)
class VariableDeclarationOp(Op):
    variable_name: Value[String]
    variable_type: Value[dgen.TypeType]
    initializer: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReadVariableOp(Op):
    variable_name: Value[String]
    source: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class AssignOp(Op):
    variable_name: Value[String]
    target: Value
    value: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CompoundAssignOp(Op):
    variable_name: Value[String]
    operator: Value[String]
    target: Value
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class PreIncrementOp(Op):
    variable_name: Value[String]
    target: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class PostIncrementOp(Op):
    variable_name: Value[String]
    target: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class PreDecrementOp(Op):
    variable_name: Value[String]
    target: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class PostDecrementOp(Op):
    variable_name: Value[String]
    target: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DereferenceOp(Op):
    pointer: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class AddressOfOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SubscriptOp(Op):
    base: Value
    index: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class MemberAccessOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class PointerMemberAccessOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[String]
    arguments: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReturnOp(Op):
    value: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ModuloOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShiftLeftOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShiftRightOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LogicalNotOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ForLoopOp(Op):
    type: Type = Nil()
    initializer: Block
    condition: Block
    update: Block
    body: Block

@dataclass(eq=False, kw_only=True)
class DoWhileOp(Op):
    initial: Value
    type: Type = Nil()
    body: Block
    condition: Block

@dataclass(eq=False, kw_only=True)
class SwitchOp(Op):
    case_values: Value[Span]
    selector: Value
    type: Type = Nil()
    default_body: Block

@dataclass(eq=False, kw_only=True)
class BreakOp(Op):
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ContinueOp(Op):
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class SizeofOp(Op):
    target_type: Value[dgen.TypeType]
    type: Type

@dataclass(eq=False, kw_only=True)
class CommaOp(Op):
    lhs: Value
    rhs: Value
    type: Type
