# GENERATED by dgen from actor.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import HasSingleBlock, Index, Nil

actor = Dialect("actor")

@dataclass(eq=False, kw_only=True)
class ActorOp(HasSingleBlock, Op):
    consume_rate: Value[Index]
    produce_rate: Value[Index]
    input: Value
    type: Type = Nil()
    body: Block

@dataclass(eq=False, kw_only=True)
class ProduceOp(Op):
    value: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class PipelineOp(HasSingleBlock, Op):
    input: Value
    type: Type
    body: Block
