# GENERATED by dgen from c.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Span, String
from dgen.dialects.index import Index

c = Dialect("c")

@dataclass(frozen=True, eq=False)
class CInt(Type):
    bits: Value[Index]
    signed: Value[Index]

@dataclass(frozen=True, eq=False)
class CFloat(Type):
    kind: Value[Index]

@dataclass(frozen=True, eq=False)
class CVoid(Type): ...

@dataclass(frozen=True, eq=False)
class CPtr(Type):
    pointee: Value[dgen.TypeType]

@dataclass(frozen=True, eq=False)
class CArray(Type):
    element: Value[dgen.TypeType]
    count: Value[Index]

@dataclass(frozen=True, eq=False)
class CStruct(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(frozen=True, eq=False)
class CUnion(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(frozen=True, eq=False)
class CFuncType(Type):
    return_type: Value[dgen.TypeType]
    param_types: Value[dgen.TypeType]
    variadic: Value[Index]

@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SubOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DivOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ModOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class NegOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class BitnotOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LognotOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class BitandOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class BitorOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class BitxorOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShlOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShrOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class EqOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class NeOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LtOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LeOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class GtOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class GeOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LogandOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LogorOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class AllocaOp(Op):
    element_type: Value[dgen.TypeType]
    type: Type

@dataclass(eq=False, kw_only=True)
class LoadOp(Op):
    ptr: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class StoreOp(Op):
    value: Value
    ptr: Value
    type: Type = CVoid()

@dataclass(eq=False, kw_only=True)
class GepOp(Op):
    field_index: Value[Index]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ArrayIndexOp(Op):
    base: Value
    index: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class AddressOfOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DerefOp(Op):
    ptr: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CastOp(Op):
    target_type: Value[dgen.TypeType]
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class BitcastOp(Op):
    target_type: Value[dgen.TypeType]
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[String]
    arguments: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CallIndirectOp(Op):
    callee: Value
    arguments: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReturnVoidOp(Op):
    type: Type = CVoid()

@dataclass(eq=False, kw_only=True)
class ReturnValueOp(Op):
    value: Value
    type: Type = CVoid()

@dataclass(eq=False, kw_only=True)
class DoWhileOp(Op):
    init: Value
    type: Type = CVoid()
    body: Block
    condition: Block

@dataclass(eq=False, kw_only=True)
class SwitchOp(Op):
    case_values: Value[Span]
    selector: Value
    type: Type = CVoid()
    default_body: Block

@dataclass(eq=False, kw_only=True)
class BreakOp(Op):
    type: Type = CVoid()

@dataclass(eq=False, kw_only=True)
class ContinueOp(Op):
    type: Type = CVoid()

@dataclass(eq=False, kw_only=True)
class StructMemberOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class StructPtrMemberOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SizeofOp(Op):
    target_type: Value[dgen.TypeType]
    type: Type

@dataclass(eq=False, kw_only=True)
class CommaOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class TernaryOp(Op):
    condition: Value
    true_val: Value
    false_val: Value
    type: Type
