# GENERATED by dgen from c.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil, Span, String
from dgen.dialects.index import Index

c = Dialect("c")

@dataclass(frozen=True, eq=False)
class CStruct(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(frozen=True, eq=False)
class CUnion(Type):
    tag_name: Value[String]
    field_names: Value[String]
    field_types: Value[String]

@dataclass(eq=False, kw_only=True)
class ModOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShlOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ShrOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LognotOp(Op):
    operand: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class GepOp(Op):
    field_index: Value[Index]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[String]
    arguments: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CallIndirectOp(Op):
    callee: Value
    arguments: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReturnVoidOp(Op):
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ReturnValueOp(Op):
    value: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class DoWhileOp(Op):
    init: Value
    type: Type = Nil()
    body: Block
    condition: Block

@dataclass(eq=False, kw_only=True)
class SwitchOp(Op):
    case_values: Value[Span]
    selector: Value
    type: Type = Nil()
    default_body: Block

@dataclass(eq=False, kw_only=True)
class BreakOp(Op):
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ContinueOp(Op):
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class StructMemberOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class StructPtrMemberOp(Op):
    field_name: Value[String]
    base: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SizeofOp(Op):
    target_type: Value[dgen.TypeType]
    type: Type

@dataclass(eq=False, kw_only=True)
class CommaOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class TernaryOp(Op):
    condition: Value
    true_val: Value
    false_val: Value
    type: Type
