# GENERATED by dgen from affine.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Array, F64, HasSingleBlock, Index, List, Nil, Pointer

affine = Dialect("affine")

@dataclass(frozen=True, eq=False)
class Shape(Type):
    rank: Value[Index]

@dataclass(frozen=True, eq=False)
class MemRef(Type):
    shape: Value[Shape]
    dtype: Value[dgen.TypeType] = F64()

@dataclass(eq=False, kw_only=True)
class AllocOp(Op):
    shape: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DeallocOp(Op):
    input: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class LoadOp(Op):
    memref: Value
    indices: Value
    type: Type = F64()

@dataclass(eq=False, kw_only=True)
class StoreOp(Op):
    value: Value
    memref: Value
    indices: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class MulFOp(Op):
    lhs: Value
    rhs: Value
    type: Type = F64()

@dataclass(eq=False, kw_only=True)
class AddFOp(Op):
    lhs: Value
    rhs: Value
    type: Type = F64()

@dataclass(eq=False, kw_only=True)
class PrintMemrefOp(Op):
    input: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ForOp(HasSingleBlock, Op):
    lo: Value[Index]
    hi: Value[Index]
    init_args: Value
    type: Type = Nil()
    body: Block
