# GENERATED by dgen from affine.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.layout import INT, VOID, Array, Pointer
from dgen.dialects.builtin import IndexType, Nil, F64Type, HasSingleBlock

affine = Dialect("affine")


@affine.type("Shape")
@dataclass(frozen=True)
class ShapeType(Type):
    rank: Value[IndexType]
    __params__ = (("rank", IndexType),)

    @property
    def __layout__(self) -> Array:
        return Array(INT, self.rank.__constant__.unpack()[0])


@affine.type("MemRef")
@dataclass(frozen=True)
class MemRefType(Type):
    __layout__ = Pointer(VOID)
    shape: Value[ShapeType]
    dtype: Type = F64Type()
    __params__ = (
        ("shape", ShapeType),
        ("dtype", Type),
    )


@affine.op("alloc")
@dataclass(eq=False, kw_only=True)
class AllocOp(Op):
    shape: Value
    type: Type
    __operands__ = (("shape", ShapeType),)


@affine.op("dealloc")
@dataclass(eq=False, kw_only=True)
class DeallocOp(Op):
    input: Value
    type: Type = Nil()
    __operands__ = (("input", Type),)


@affine.op("load")
@dataclass(eq=False, kw_only=True)
class LoadOp(Op):
    memref: Value
    indices: Value
    type: Type = F64Type()
    __operands__ = (
        ("memref", Type),
        ("indices", IndexType),
    )


@affine.op("store")
@dataclass(eq=False, kw_only=True)
class StoreOp(Op):
    value: Value
    memref: Value
    indices: Value
    type: Type = Nil()
    __operands__ = (
        ("value", Type),
        ("memref", Type),
        ("indices", IndexType),
    )


@affine.op("mul_f")
@dataclass(eq=False, kw_only=True)
class MulFOp(Op):
    lhs: Value
    rhs: Value
    type: Type = F64Type()
    __operands__ = (
        ("lhs", Type),
        ("rhs", Type),
    )


@affine.op("add_f")
@dataclass(eq=False, kw_only=True)
class AddFOp(Op):
    lhs: Value
    rhs: Value
    type: Type = F64Type()
    __operands__ = (
        ("lhs", Type),
        ("rhs", Type),
    )


@affine.op("print_memref")
@dataclass(eq=False, kw_only=True)
class PrintMemrefOp(Op):
    input: Value
    type: Type = Nil()
    __operands__ = (("input", Type),)


@affine.op("for")
@dataclass(eq=False, kw_only=True)
class ForOp(HasSingleBlock, Op):
    lo: Value[IndexType]
    hi: Value[IndexType]
    type: Type = Nil()
    body: Block
    __params__ = (
        ("lo", IndexType),
        ("hi", IndexType),
    )
    __blocks__ = ("body",)
