# GENERATED by dgen from toy.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Op, Type, Value
from dgen.layout import Void
from dgen.dialects.builtin import IndexType, Nil, F64Type, String
from toy.dialects.affine import ShapeType

toy = Dialect("toy")


@toy.type("Tensor")
@dataclass(frozen=True)
class TensorType(Type):
    shape: Value[ShapeType]
    dtype: Type = F64Type()
    __params__ = (
        ("shape", ShapeType),
        ("dtype", Type),
    )


@toy.type("InferredShapeTensor")
@dataclass(frozen=True)
class InferredShapeTensor(Type):
    __layout__ = Void()
    dtype: Type = F64Type()
    __params__ = (("dtype", Type),)


@toy.op("transpose")
@dataclass(eq=False, kw_only=True)
class TransposeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Type),)


@toy.op("reshape")
@dataclass(eq=False, kw_only=True)
class ReshapeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Type),)


@toy.op("mul")
@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (
        ("lhs", Type),
        ("rhs", Type),
    )


@toy.op("add")
@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (
        ("lhs", Type),
        ("rhs", Type),
    )


@toy.op("generic_call")
@dataclass(eq=False, kw_only=True)
class GenericCallOp(Op):
    callee: Value[String]
    args: list[Value]
    type: Type
    __params__ = (("callee", String),)
    __operands__ = (("args", Type),)


@toy.op("concat")
@dataclass(eq=False, kw_only=True)
class ConcatOp(Op):
    axis: Value[IndexType]
    lhs: Value
    rhs: Value
    type: Type
    __params__ = (("axis", IndexType),)
    __operands__ = (
        ("lhs", Type),
        ("rhs", Type),
    )


@toy.op("tile")
@dataclass(eq=False, kw_only=True)
class TileOp(Op):
    count: Value[IndexType]
    input: Value
    type: Type
    __params__ = (("count", IndexType),)
    __operands__ = (("input", Type),)


@toy.op("nonzero_count")
@dataclass(eq=False, kw_only=True)
class NonzeroCountOp(Op):
    input: Value
    type: Type = IndexType()
    __operands__ = (("input", Type),)


@toy.op("dim_size")
@dataclass(eq=False, kw_only=True)
class DimSizeOp(Op):
    axis: Value[IndexType]
    input: Value
    type: Type = IndexType()
    __params__ = (("axis", IndexType),)
    __operands__ = (("input", Type),)


@toy.op("print")
@dataclass(eq=False, kw_only=True)
class PrintOp(Op):
    input: Value
    type: Type = Nil()
    __operands__ = (("input", Type),)
