# GENERATED by dgen from toy.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
import toy.dialects.memory as memory
from dgen.dialects.builtin import F64, Nil
from dgen.dialects.index import Index

toy = Dialect("toy")

@dataclass(frozen=True, eq=False)
class Tensor(Type):
    shape: Value[memory.Shape]
    dtype: Value[dgen.TypeType] = F64()

@dataclass(frozen=True, eq=False)
class InferredShapeTensor(Type):
    dtype: Value[dgen.TypeType] = F64()

@dataclass(eq=False, kw_only=True)
class TransposeOp(Op):
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReshapeOp(Op):
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ConcatOp(Op):
    axis: Value[Index]
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class TileOp(Op):
    count: Value[Index]
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class NonzeroCountOp(Op):
    input: Value
    type: Type = Index()

@dataclass(eq=False, kw_only=True)
class DimSizeOp(Op):
    axis: Value[Index]
    input: Value
    type: Type = Index()

@dataclass(eq=False, kw_only=True)
class PrintOp(Op):
    input: Value
    type: Type = Nil()
