# GENERATED by dgen from toy.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value, layout
from dgen.dialects.builtin import Index, Nil, F64, String, FatPointer
import toy.dialects.affine as affine

toy = Dialect("toy")


@toy.type("Tensor")
@dataclass(frozen=True)
class Tensor(Type):
    shape: Value[affine.Shape]
    dtype: Value[dgen.TypeType] = F64()
    __params__ = (("shape", affine.Shape), ("dtype", dgen.TypeType),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.FatPointer(dgen.type.type_constant(self.dtype).__layout__)


@toy.type("InferredShapeTensor")
@dataclass(frozen=True)
class InferredShapeTensor(Type):
    __layout__ = Nil.__layout__
    dtype: Value[dgen.TypeType] = F64()
    __params__ = (("dtype", dgen.TypeType),)


@toy.op("transpose")
@dataclass(eq=False, kw_only=True)
class TransposeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Tensor),)


@toy.op("reshape")
@dataclass(eq=False, kw_only=True)
class ReshapeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Tensor),)


@toy.op("mul")
@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (("lhs", Tensor), ("rhs", Tensor),)


@toy.op("add")
@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (("lhs", Tensor), ("rhs", Tensor),)


@toy.op("concat")
@dataclass(eq=False, kw_only=True)
class ConcatOp(Op):
    axis: Value[Index]
    lhs: Value
    rhs: Value
    type: Type
    __params__ = (("axis", Index),)
    __operands__ = (("lhs", Tensor), ("rhs", Tensor),)
    __constraints__ = ("axis < lhs.shape.rank",)


@toy.op("tile")
@dataclass(eq=False, kw_only=True)
class TileOp(Op):
    count: Value[Index]
    input: Value
    type: Type
    __params__ = (("count", Index),)
    __operands__ = (("input", Tensor),)


@toy.op("nonzero_count")
@dataclass(eq=False, kw_only=True)
class NonzeroCountOp(Op):
    input: Value
    type: Type = Index()
    __operands__ = (("input", Tensor),)


@toy.op("dim_size")
@dataclass(eq=False, kw_only=True)
class DimSizeOp(Op):
    axis: Value[Index]
    input: Value
    type: Type = Index()
    __params__ = (("axis", Index),)
    __operands__ = (("input", Tensor),)
    __constraints__ = ("axis < input.shape.rank",)


@toy.op("print")
@dataclass(eq=False, kw_only=True)
class PrintOp(Op):
    input: Value
    type: Type = Nil()
    __operands__ = (("input", Tensor),)


