# GENERATED by dgen from toy.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Op, Type, Value, layout
from dgen.dialects.builtin import Index, Nil, F64, String
from toy.dialects.affine import Shape

toy = Dialect("toy")


@toy.type("Tensor")
@dataclass(frozen=True)
class Tensor(Type):
    shape: Value[Shape]
    dtype: Type = F64()
    __params__ = (("shape", Shape), ("dtype", Type),)


@toy.type("InferredShapeTensor")
@dataclass(frozen=True)
class InferredShapeTensor(Type):
    __layout__ = layout.Void()
    dtype: Type = F64()
    __params__ = (("dtype", Type),)


@toy.op("transpose")
@dataclass(eq=False, kw_only=True)
class TransposeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Type),)


@toy.op("reshape")
@dataclass(eq=False, kw_only=True)
class ReshapeOp(Op):
    input: Value
    type: Type
    __operands__ = (("input", Type),)


@toy.op("mul")
@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (("lhs", Type), ("rhs", Type),)


@toy.op("add")
@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type
    __operands__ = (("lhs", Type), ("rhs", Type),)


@toy.op("generic_call")
@dataclass(eq=False, kw_only=True)
class GenericCallOp(Op):
    callee: Value[String]
    args: list[Value]
    type: Type
    __params__ = (("callee", String),)
    __operands__ = (("args", Type),)


@toy.op("concat")
@dataclass(eq=False, kw_only=True)
class ConcatOp(Op):
    axis: Value[Index]
    lhs: Value
    rhs: Value
    type: Type
    __params__ = (("axis", Index),)
    __operands__ = (("lhs", Type), ("rhs", Type),)


@toy.op("tile")
@dataclass(eq=False, kw_only=True)
class TileOp(Op):
    count: Value[Index]
    input: Value
    type: Type
    __params__ = (("count", Index),)
    __operands__ = (("input", Type),)


@toy.op("nonzero_count")
@dataclass(eq=False, kw_only=True)
class NonzeroCountOp(Op):
    input: Value
    type: Type = Index()
    __operands__ = (("input", Type),)


@toy.op("dim_size")
@dataclass(eq=False, kw_only=True)
class DimSizeOp(Op):
    axis: Value[Index]
    input: Value
    type: Type = Index()
    __params__ = (("axis", Index),)
    __operands__ = (("input", Type),)


@toy.op("print")
@dataclass(eq=False, kw_only=True)
class PrintOp(Op):
    input: Value
    type: Type = Nil()
    __operands__ = (("input", Type),)


