# GENERATED by dgen from algebra.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Op, Trait, Type, Value

algebra = Dialect("algebra")

class AddMagma(Trait): ...
class MulMagma(Trait): ...
class TotalOrder(Trait): ...

@dataclass(eq=False)
class AddOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class NegateOp(Op):
    input: Value
    type: Type

@dataclass(eq=False)
class SubtractOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class MultiplyOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class ReciprocalOp(Op):
    input: Value
    type: Type

@dataclass(eq=False)
class DivideOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class MeetOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class JoinOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class ComplementOp(Op):
    input: Value
    type: Type

@dataclass(eq=False)
class SymmetricDifferenceOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class EqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class NotEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class LessThanOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class LessEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class GreaterThanOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class GreaterEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False)
class CastOp(Op):
    input: Value
    type: Type
