# GENERATED by dgen from algebra.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Trait, Type, Value
from dgen.dialects.builtin import Nil

algebra = Dialect("algebra")

class AddMagma(Trait):
    __params__ = ()
    __operands__ = ()
    __blocks__ = ()
    __constraints__ = ()
    name = None
    type = <functools.cached_property object at 0x7effc69cbe10>
    __layout__ = <property object at 0x7effc69cede0>
    dialect = <dgen.dialect.Dialect object at 0x7effc676e350>
    asm_name = 'AddMagma'

class MulMagma(Trait):
    __params__ = ()
    __operands__ = ()
    __blocks__ = ()
    __constraints__ = ()
    name = None
    type = <functools.cached_property object at 0x7effc69cbe10>
    __layout__ = <property object at 0x7effc69cede0>
    dialect = <dgen.dialect.Dialect object at 0x7effc676e350>
    asm_name = 'MulMagma'

class TotalOrder(Trait):
    __params__ = ()
    __operands__ = ()
    __blocks__ = ()
    __constraints__ = ()
    name = None
    type = <functools.cached_property object at 0x7effc69cbe10>
    __layout__ = <property object at 0x7effc69cede0>
    dialect = <dgen.dialect.Dialect object at 0x7effc676e350>
    asm_name = 'TotalOrder'

@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class NegateOp(Op):
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SubtractOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class MultiplyOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ReciprocalOp(Op):
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DivideOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class MeetOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class JoinOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ComplementOp(Op):
    input: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class SymmetricDifferenceOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class EqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class NotEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LessThanOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class LessEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class GreaterThanOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class GreaterEqualOp(Op):
    left: Value
    right: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class CastOp(Op):
    input: Value
    type: Type

