# GENERATED by dgen from builtin.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value, layout

builtin = Dialect("builtin")


class HasSingleBlock:
    pass


@builtin.type("Index")
@dataclass(frozen=True)
class Index(Type):
    __layout__ = layout.Int()


@builtin.type("F64")
@dataclass(frozen=True)
class F64(Type):
    __layout__ = layout.Float64()


@builtin.type("Nil")
@dataclass(frozen=True)
class Nil(Type):
    __layout__ = layout.Void()


@builtin.type("String")
@dataclass(frozen=True)
class String(Type):
    __layout__ = layout.String()


@builtin.type("TypeTag")
@dataclass(frozen=True)
class TypeTag(Type):
    __layout__ = String.__layout__


@builtin.type("Byte")
@dataclass(frozen=True)
class Byte(Type):
    __layout__ = layout.Byte()


@builtin.type("Array")
@dataclass(frozen=True)
class Array(Type):
    element_type: Value[dgen.TypeType]
    n: Value[Index]
    __params__ = (
        ("element_type", dgen.TypeType),
        ("n", Index),
    )

    @property
    def __layout__(self) -> layout.Layout:
        return layout.Array(
            dgen.type.type_constant(self.element_type).__layout__,
            self.n.__constant__.to_json(),
        )


@builtin.type("Pointer")
@dataclass(frozen=True)
class Pointer(Type):
    pointee: Value[dgen.TypeType]
    __params__ = (("pointee", dgen.TypeType),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.Pointer(dgen.type.type_constant(self.pointee).__layout__)


@builtin.type("FatPointer")
@dataclass(frozen=True)
class FatPointer(Type):
    pointee: Value[dgen.TypeType]
    __params__ = (("pointee", dgen.TypeType),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.FatPointer(dgen.type.type_constant(self.pointee).__layout__)


@builtin.type("List")
@dataclass(frozen=True)
class List(Type):
    element_type: Value[dgen.TypeType]
    __params__ = (("element_type", dgen.TypeType),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.FatPointer(dgen.type.type_constant(self.element_type).__layout__)


@builtin.type("Tuple")
@dataclass(frozen=True)
class Tuple(Type):
    types: list[Value[dgen.TypeType]]
    __params__ = (("types", List),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.Record(
            [
                (str(i), dgen.type.type_constant(t).__layout__)
                for i, t in enumerate(self.types)
            ]
        )


@builtin.type("Function")
@dataclass(frozen=True)
class Function(Type):
    __layout__ = layout.Void()
    result: Value[dgen.TypeType]
    __params__ = (("result", dgen.TypeType),)


@builtin.op("pack")
@dataclass(eq=False, kw_only=True)
class PackOp(Op):
    values: list[Value]
    type: Type
    __operands__ = (("values", Type),)


@builtin.op("list_get")
@dataclass(eq=False, kw_only=True)
class ListGetOp(Op):
    index: Value[Index]
    list: Value
    type: Type
    __params__ = (("index", Index),)
    __operands__ = (("list", List),)


@builtin.op("add_index")
@dataclass(eq=False, kw_only=True)
class AddIndexOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Index()
    __operands__ = (
        ("lhs", Index),
        ("rhs", Index),
    )


@builtin.op("equal_index")
@dataclass(eq=False, kw_only=True)
class EqualIndexOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Index()
    __operands__ = (
        ("lhs", Index),
        ("rhs", Index),
    )


@builtin.op("subtract_index")
@dataclass(eq=False, kw_only=True)
class SubtractIndexOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Index()
    __operands__ = (
        ("lhs", Index),
        ("rhs", Index),
    )


@builtin.op("return")
@dataclass(eq=False, kw_only=True)
class ReturnOp(Op):
    value: Value | Nil = Nil()
    type: Type = Nil()
    __operands__ = (("value", Type),)


@builtin.op("function")
@dataclass(eq=False, kw_only=True)
class FunctionOp(HasSingleBlock, Op):
    result: Value[dgen.TypeType]
    type: Type = Nil()
    body: Block
    __params__ = (("result", dgen.TypeType),)
    __blocks__ = ("body",)


@builtin.op("if")
@dataclass(eq=False, kw_only=True)
class IfOp(Op):
    cond: Value
    type: Type
    then_body: Block
    else_body: Block
    __operands__ = (("cond", Index),)
    __blocks__ = (
        "then_body",
        "else_body",
    )


@builtin.op("call")
@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[Function]
    args: list[Value]
    type: Type
    __params__ = (("callee", Function),)
    __operands__ = (("args", Type),)
