# GENERATED by dgen from builtin.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.layout import Byte, FatPointer, Float64, Int, StringLayout, Void

builtin = Dialect("builtin")


class HasSingleBlock:
    pass


@builtin.type("index")
@dataclass(frozen=True)
class IndexType(Type):
    __layout__ = Int()


@builtin.type("f64")
@dataclass(frozen=True)
class F64Type(Type):
    __layout__ = Float64()


@builtin.type("Nil")
@dataclass(frozen=True)
class Nil(Type):
    __layout__ = Void()


@builtin.type("String")
@dataclass(frozen=True)
class String(Type):
    __layout__ = StringLayout(Byte())


@builtin.type("List")
@dataclass(frozen=True)
class List(Type):
    element_type: Type
    __params__ = (("element_type", Type),)

    @property
    def __layout__(self) -> FatPointer:
        return FatPointer(self.element_type.__layout__)


@builtin.op("pack")
@dataclass(eq=False, kw_only=True)
class PackOp(Op):
    values: list[Value]
    type: Type
    __operands__ = (("values", Type),)


@builtin.op("list_get")
@dataclass(eq=False, kw_only=True)
class ListGetOp(Op):
    index: Value[IndexType]
    list: Value
    type: Type
    __params__ = (("index", IndexType),)
    __operands__ = (("list", List),)


@builtin.op("add_index")
@dataclass(eq=False, kw_only=True)
class AddIndexOp(Op):
    lhs: Value
    rhs: Value
    type: Type = IndexType()
    __operands__ = (
        ("lhs", IndexType),
        ("rhs", IndexType),
    )


@builtin.op("return")
@dataclass(eq=False, kw_only=True)
class ReturnOp(Op):
    value: Value | Nil = Nil()
    type: Type = Nil()
    __operands__ = (("value", Type),)


@builtin.op("function")
@dataclass(eq=False, kw_only=True)
class FunctionOp(HasSingleBlock, Op):
    type: Type
    body: Block
    __blocks__ = ("body",)
