# GENERATED by dgen from builtin.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value, layout

builtin = Dialect("builtin")


class HasSingleBlock:
    pass


@builtin.type("Index")
@dataclass(frozen=True)
class Index(Type):
    __layout__ = layout.Int()


@builtin.type("F64")
@dataclass(frozen=True)
class F64(Type):
    __layout__ = layout.Float64()


@builtin.type("Nil")
@dataclass(frozen=True)
class Nil(Type):
    __layout__ = layout.Void()


@builtin.type("String")
@dataclass(frozen=True)
class String(Type):
    __layout__ = layout.String()


@builtin.type("Byte")
@dataclass(frozen=True)
class Byte(Type):
    __layout__ = layout.Byte()


@builtin.type("Array")
@dataclass(frozen=True)
class Array(Type):
    element_type: Type
    n: Value[Index]
    __params__ = (
        ("element_type", Type),
        ("n", Index),
    )

    @property
    def __layout__(self) -> layout.Layout:
        return layout.Array(self.element_type.__layout__, self.n.__constant__.to_json())


@builtin.type("Pointer")
@dataclass(frozen=True)
class Pointer(Type):
    pointee: Type
    __params__ = (("pointee", Type),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.Pointer(self.pointee.__layout__)


@builtin.type("FatPointer")
@dataclass(frozen=True)
class FatPointer(Type):
    pointee: Type
    __params__ = (("pointee", Type),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.FatPointer(self.pointee.__layout__)


@builtin.type("List")
@dataclass(frozen=True)
class List(Type):
    element_type: Type
    __params__ = (("element_type", Type),)

    @property
    def __layout__(self) -> layout.Layout:
        return layout.FatPointer(self.element_type.__layout__)


@builtin.op("pack")
@dataclass(eq=False, kw_only=True)
class PackOp(Op):
    values: list[Value]
    type: Type
    __operands__ = (("values", Type),)


@builtin.op("list_get")
@dataclass(eq=False, kw_only=True)
class ListGetOp(Op):
    index: Value[Index]
    list: Value
    type: Type
    __params__ = (("index", Index),)
    __operands__ = (("list", List),)


@builtin.op("add_index")
@dataclass(eq=False, kw_only=True)
class AddIndexOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Index()
    __operands__ = (
        ("lhs", Index),
        ("rhs", Index),
    )


@builtin.op("return")
@dataclass(eq=False, kw_only=True)
class ReturnOp(Op):
    value: Value | Nil = Nil()
    type: Type = Nil()
    __operands__ = (("value", Type),)


@builtin.op("function")
@dataclass(eq=False, kw_only=True)
class FunctionOp(HasSingleBlock, Op):
    type: Type
    body: Block
    __blocks__ = ("body",)
