# GENERATED by dgen from builtin.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Trait, Type, Value
from dgen.dialects.index import Index

builtin = Dialect("builtin")

class Effect(Trait): ...

@dataclass(eq=False)
class Handler(Trait):
    effect_type: Value[dgen.TypeType]

@dataclass(eq=False)
class Nil(Type): ...

@dataclass(eq=False)
class Never(Type): ...

@dataclass(eq=False)
class String(Type): ...

@dataclass(eq=False)
class TypeTag(Type): ...

@dataclass(eq=False)
class Byte(Type): ...

@dataclass(eq=False)
class Array(Type):
    element_type: Value[dgen.TypeType]
    n: Value[Index]

@dataclass(eq=False)
class Pointer(Type):
    pointee: Value[dgen.TypeType]

@dataclass(eq=False)
class Span(Type):
    pointee: Value[dgen.TypeType]

@dataclass(eq=False)
class Tuple(Type):
    types: Value[Span]

@dataclass(eq=False)
class ChainOp(Op):
    lhs: Value
    rhs: Value
    type: Type

@dataclass(eq=False)
class TypeOp(Op):
    value: Value
    type: Type = dgen.TypeType()

@dataclass(eq=False)
class ExternOp(Op):
    symbol: Value[String]
    type: Type
