# GENERATED by dgen from builtin.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
from dgen.dialects.index import Index

builtin = Dialect("builtin")

class HasSingleBlock: ...

@dataclass(frozen=True, eq=False)
class Nil(Type): ...

@dataclass(frozen=True, eq=False)
class String(Type): ...

@dataclass(frozen=True, eq=False)
class TypeTag(Type): ...

@dataclass(frozen=True, eq=False)
class Byte(Type): ...

@dataclass(frozen=True, eq=False)
class Array(Type):
    element_type: Value[dgen.TypeType]
    n: Value[Index]

@dataclass(frozen=True, eq=False)
class Pointer(Type):
    pointee: Value[dgen.TypeType]

@dataclass(frozen=True, eq=False)
class Span(Type):
    pointee: Value[dgen.TypeType]

@dataclass(frozen=True, eq=False)
class List(Type):
    element_type: Value[dgen.TypeType]

@dataclass(frozen=True, eq=False)
class Tuple(Type):
    types: list[Value[dgen.TypeType]]

@dataclass(eq=False, kw_only=True)
class ListGetOp(Op):
    index: Value[Index]
    list: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class ChainOp(Op):
    lhs: Value
    rhs: Value
    type: Type
