# GENERATED by dgen from control_flow.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import HasSingleBlock, Index, Nil

control_flow = Dialect("control_flow")

@dataclass(eq=False, kw_only=True)
class ForOp(HasSingleBlock, Op):
    lower_bound: Value[Index]
    upper_bound: Value[Index]
    initial_arguments: Value
    type: Type = Nil()
    body: Block

@dataclass(eq=False, kw_only=True)
class IfOp(Op):
    condition: Value
    then_arguments: Value
    else_arguments: Value
    type: Type
    then_body: Block
    else_body: Block
