# GENERATED by dgen from control_flow.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Never, Nil
from dgen.dialects.index import Index

control_flow = Dialect("control_flow")

@dataclass(eq=False)
class ForOp(Op):
    lower_bound: Value[Index]
    upper_bound: Value[Index]
    initial_arguments: Value
    body: Block
    type: Type = Nil()

@dataclass(eq=False)
class WhileOp(Op):
    initial_arguments: Value
    condition: Block
    body: Block
    type: Type = Nil()

@dataclass(eq=False)
class IfOp(Op):
    condition: Value
    then_arguments: Value
    else_arguments: Value
    then_body: Block
    else_body: Block
    type: Type

@dataclass(eq=False)
class BreakOp(Op):
    type: Type = Never()

@dataclass(eq=False)
class ContinueOp(Op):
    type: Type = Never()
