# GENERATED by dgen from error.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
from dgen.dialects.builtin import Effect, Never

error = Dialect("error")

@dataclass(eq=False)
class Raise(Effect, Type):
    error_type: Value[dgen.TypeType]

@dataclass(eq=False)
class RaiseHandler(Type):
    error_type: Value[dgen.TypeType]

@dataclass(eq=False)
class RaiseOp(Op):
    error_type: Value[dgen.TypeType]
    handler: Value[RaiseHandler]
    error: Value
    type: Type = Never()
