# GENERATED by dgen from error.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Never

error = Dialect("error")

@dataclass(eq=False)
class Raise(Type):
    error_type: Value[dgen.TypeType]

@dataclass(eq=False)
class RaiseHandler(Type):
    error_type: Value[dgen.TypeType]

@dataclass(eq=False)
class RaiseOp(Op):
    error_type: Value[dgen.TypeType]
    handler: Value
    error: Value
    type: Type = Never()

@dataclass(eq=False)
class TryOp(Op):
    error_type: Value[dgen.TypeType]
    body: Block
    except_: Block
    type: Type
