# GENERATED by dgen from existential.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
import dgen.dialects.memory as memory
from dgen.dialects.builtin import Byte

existential = Dialect("existential")

@dataclass(eq=False)
class Some(Type):
    bound: Value[dgen.TypeType]

@dataclass(eq=False)
class Any(Type):
    ...

@dataclass(eq=False)
class PackOp(Op):
    bound: Value[dgen.TypeType]
    value: Value
    type: Type

@dataclass(eq=False)
class UnpackOp(Op):
    witness: Value[dgen.TypeType]
    box: Value
    type: Type

