# GENERATED by dgen from existential.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value

existential = Dialect("existential")

@dataclass(eq=False)
class Some(Type):
    bound: Value[dgen.TypeType]

@dataclass(eq=False)
class Any(Type): ...

@dataclass(eq=False)
class PackOp(Op):
    value: Value
    type: Type

@dataclass(eq=False)
class UnpackOp(Op):
    box: Value
    type: Type
