# GENERATED by dgen from function.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil, Span

function = Dialect("function")

@dataclass(eq=False)
class Function(Type):
    arguments: Value[Span]
    result_type: Value[dgen.TypeType]

@dataclass(eq=False)
class FunctionOp(Op):
    result_type: Value[dgen.TypeType]
    body: Block
    type: Type

@dataclass(eq=False)
class CallOp(Op):
    callee: Value[Function]
    arguments: Value
    type: Type
