# GENERATED by dgen from function.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil, Span

function = Dialect("function")

@dataclass(frozen=True, eq=False)
class Function(Type):
    result: Value[dgen.TypeType]

@dataclass(eq=False, kw_only=True)
class FunctionOp(Op):
    result: Value[dgen.TypeType]
    type: Type
    body: Block

@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[Function]
    arguments: Value
    type: Type
