# GENERATED by dgen from goto.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil, Span

goto = Dialect("goto")

@dataclass(eq=False)
class Label(Type):
    ...

@dataclass(eq=False)
class RegionOp(Op):
    initial_arguments: Value
    body: Block
    type: Type = Label()

@dataclass(eq=False)
class LabelOp(Op):
    initial_arguments: Value
    body: Block
    type: Type = Label()

@dataclass(eq=False)
class BranchOp(Op):
    target: Value[Label]
    arguments: Value
    type: Type = Nil()

@dataclass(eq=False)
class ConditionalBranchOp(Op):
    true_target: Value[Label]
    false_target: Value[Label]
    condition: Value
    true_arguments: Value
    false_arguments: Value
    type: Type = Nil()

