# GENERATED by dgen from goto.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil

goto = Dialect("goto")

@dataclass(frozen=True, eq=False)
class Label(Type): ...

@dataclass(eq=False, kw_only=True)
class LabelOp(Op):
    initial_arguments: Value
    type: Type = Label()
    body: Block

@dataclass(eq=False, kw_only=True)
class BranchOp(Op):
    target: Value[Label]
    arguments: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class ConditionalBranchOp(Op):
    true_target: Value[Label]
    false_target: Value[Label]
    condition: Value
    true_arguments: Value
    false_arguments: Value
    type: Type = Nil()
