# GENERATED by dgen from index.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Type

index = Dialect("index")

@dataclass(eq=False)
class Index(Type): ...
