# GENERATED by dgen from index.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Op, Type, Value

index = Dialect("index")

@dataclass(frozen=True, eq=False)
class Index(Type): ...

@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    left: Value
    right: Value
    type: Type = Index()

@dataclass(eq=False, kw_only=True)
class SubtractOp(Op):
    left: Value
    right: Value
    type: Type = Index()

@dataclass(eq=False, kw_only=True)
class EqualOp(Op):
    left: Value
    right: Value
    type: Type = Index()
