# GENERATED by dgen from index.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value

index = Dialect("index")

@dataclass(eq=False)
class Index(Type): ...
