# GENERATED by dgen from llvm.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Block, Dialect, Op, Type, Value
from dgen.dialects.builtin import F64, Index, List, Nil, Pointer, String

llvm = Dialect("llvm")

@dataclass(frozen=True)
class Ptr(Type):
    ...

@dataclass(frozen=True)
class Int(Type):
    bits: Value[Index]

@dataclass(frozen=True)
class Float(Type):
    ...

@dataclass(frozen=True)
class Void(Type):
    ...

@dataclass(frozen=True)
class Label(Type):
    ...

@dataclass(eq=False, kw_only=True)
class AllocaOp(Op):
    elem_count: Value[Index]
    type: Type = Ptr()

@dataclass(eq=False, kw_only=True)
class GepOp(Op):
    base: Value
    index: Value
    type: Type = Ptr()

@dataclass(eq=False, kw_only=True)
class LoadOp(Op):
    ptr: Value
    type: Type = Float()

@dataclass(eq=False, kw_only=True)
class StoreOp(Op):
    value: Value
    ptr: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class FaddOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Float()

@dataclass(eq=False, kw_only=True)
class FmulOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Float()

@dataclass(eq=False, kw_only=True)
class AddOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Int(bits=Index().constant(64))

@dataclass(eq=False, kw_only=True)
class SubOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Int(bits=Index().constant(64))

@dataclass(eq=False, kw_only=True)
class MulOp(Op):
    lhs: Value
    rhs: Value
    type: Type = Int(bits=Index().constant(64))

@dataclass(eq=False, kw_only=True)
class IcmpOp(Op):
    pred: Value[String]
    lhs: Value
    rhs: Value
    type: Type = Int(bits=Index().constant(1))

@dataclass(eq=False, kw_only=True)
class LabelOp(Op):
    type: Type = Label()
    body: Block

@dataclass(eq=False, kw_only=True)
class BrOp(Op):
    target: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class CondBrOp(Op):
    cond: Value
    true_target: Value
    false_target: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class PhiOp(Op):
    label_a: Value[Label]
    label_b: Value[Label]
    a: Value
    b: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class FcmpOp(Op):
    pred: Value[String]
    lhs: Value
    rhs: Value
    type: Type = Int(bits=Index().constant(1))

@dataclass(eq=False, kw_only=True)
class ZextOp(Op):
    input: Value
    type: Type = Int(bits=Index().constant(64))

@dataclass(eq=False, kw_only=True)
class CallOp(Op):
    callee: Value[String]
    args: Value
    type: Type = Nil()

