# GENERATED by dgen from memory.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
from dgen.dialects.builtin import Nil

memory = Dialect("memory")

@dataclass(frozen=True, eq=False)
class Reference(Type):
    element_type: Value[dgen.TypeType]

@dataclass(eq=False, kw_only=True)
class StackAllocateOp(Op):
    element_type: Value[dgen.TypeType]
    type: Type

@dataclass(eq=False, kw_only=True)
class HeapAllocateOp(Op):
    element_type: Value[dgen.TypeType]
    count: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class DeallocateOp(Op):
    ptr: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class LoadOp(Op):
    ptr: Value
    type: Type

@dataclass(eq=False, kw_only=True)
class StoreOp(Op):
    value: Value
    ptr: Value
    type: Type = Nil()

@dataclass(eq=False, kw_only=True)
class OffsetOp(Op):
    ptr: Value
    index: Value
    type: Type
