# GENERATED by dgen from ndbuffer.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
from dgen.dialects.builtin import Array, Nil, Pointer
from dgen.dialects.index import Index
from dgen.dialects.number import Float64

ndbuffer = Dialect("ndbuffer")

@dataclass(eq=False)
class Shape(Type):
    rank: Value[Index]

@dataclass(eq=False)
class NDBuffer(Type):
    shape: Value[Shape]
    dtype: Value[dgen.TypeType] = Float64()

@dataclass(eq=False)
class AllocOp(Op):
    shape: Value
    type: Type

@dataclass(eq=False)
class DeallocOp(Op):
    mem: Value
    input: Value
    type: Type = Nil()

@dataclass(eq=False)
class LoadOp(Op):
    mem: Value
    memref: Value
    indices: Value
    type: Type = Float64()

@dataclass(eq=False)
class StoreOp(Op):
    mem: Value
    value: Value
    memref: Value
    indices: Value
    type: Type = Nil()

@dataclass(eq=False)
class PrintMemrefOp(Op):
    input: Value
    type: Type = Nil()

