# GENERATED by dgen from number.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

from dgen import Dialect, Type, Value
from dgen.dialects.index import Index

number = Dialect("number")

@dataclass(frozen=True, eq=False)
class Boolean(Type): ...

@dataclass(frozen=True, eq=False)
class SignedInteger(Type):
    bits: Value[Index]

@dataclass(frozen=True, eq=False)
class UnsignedInteger(Type):
    bits: Value[Index]

@dataclass(frozen=True, eq=False)
class Float64(Type): ...
