# GENERATED by dgen from number.dgen — do not edit.

from __future__ import annotations

from dataclasses import dataclass

import dgen
from dgen import Dialect, Op, Type, Value
from dgen.dialects.builtin import Byte, F64
from dgen.dialects.index import Index

number = Dialect("number")

@dataclass(frozen=True, eq=False)
class Boolean(Type):
    ...

@dataclass(frozen=True, eq=False)
class SignedInteger(Type):
    bits: Value[Index]

@dataclass(frozen=True, eq=False)
class UnsignedInteger(Type):
    bits: Value[Index]

@dataclass(frozen=True, eq=False)
class Float64(Type):
    ...

